### Question 1
Create a numpy array containing the numbers from 1 to 10, and then reshape it to a 2x5 matrix.

In [11]:
import numpy as np
a1 = np.arange(1, 11)
matrix_a1 = a1.reshape(2, 5)
print(matrix_a1)
print(matrix_a1.shape)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)


### Questio 2
Create a numpy array containing the numbers from 1 to 20, and then extract the elements between the 5th and 15th index.

In [7]:
import numpy as np
a2=np.arange(1,21)
print(a2[5:16])

[ 6  7  8  9 10 11 12 13 14 15 16]


### Question 3
Create a Pandas series with the following data: {'apples': 3, 'bananas': 2, 'oranges': 1}. 
Then, add a new item to the series with the key 'pears' and the value 4.

In [10]:
import pandas as pd

# Create a Pandas series with the given data
data = {'apples': 3, 'bananas': 2, 'oranges': 1}
series = pd.Series(data)

# Add a new item to the series
series['pears'] = 4

# Display the updated series
print(series)


apples     3
bananas    2
oranges    1
pears      4
dtype: int64


### Question 4
Create a dataframe with the following columns: name, age, and gender. The dataframe should have 10 rows of data.


In [2]:
import pandas as pd

data = {
    'name': ['Aravind', 'Ritwik', 'Harry', 'Lal', 'Malu', 'Nirupa', 'Grace', 'Annie', 'Akhil', 'Maya'],
    'age': [23, 34, 45, 28, 33, 36, 29, 40, 22, 26],
    'gender': ['Male', 'Male', 'Male', 'Male', 'Female', 'Female', 'Female', 'Female', 'Male', 'Female']
}

df = pd.DataFrame(data)

print(df)


      name  age  gender
0  Aravind   23    Male
1   Ritwik   34    Male
2    Harry   45    Male
3      Lal   28    Male
4     Malu   33  Female
5   Nirupa   36  Female
6    Grace   29  Female
7    Annie   40  Female
8    Akhil   22    Male
9     Maya   26  Female


### Question 5
Add a new column to the data frame created in question 1, called occupation. The values for this column should be Programmer, Manager, and Analyst, corresponding to the rows in the dataframe.


In [6]:
df['occupation'] = ['Programmer', 'Manager', 'Analyst', 'Teacher', 'Manager', 
                     'Analyst', 'Programmer', 'Manager', 'Analyst', 'Teacher']
print(df)


      name  age  gender  occupation
0  Aravind   23    Male  Programmer
1   Ritwik   34    Male     Manager
2    Harry   45    Male     Analyst
3      Lal   28    Male     Teacher
4     Malu   33  Female     Manager
5   Nirupa   36  Female     Analyst
6    Grace   29  Female  Programmer
7    Annie   40  Female     Manager
8    Akhil   22    Male     Analyst
9     Maya   26  Female     Teacher


### Question 6
Select the rows of the dataframe where the age is greater than or equal to 30.


In [9]:
updated_df = df[df['age'] >= 30]

print(updated_df)


     name  age  gender occupation
1  Ritwik   34    Male    Manager
2   Harry   45    Male    Analyst
4    Malu   33  Female    Manager
5  Nirupa   36  Female    Analyst
7   Annie   40  Female    Manager


### Question 7
Convert this dataframe to a csv file and read that csv file, finally display the contents.


In [10]:
# Save the DataFrame to a CSV file
df.to_csv('dataframe.csv', index=False)

# Read the CSV file back into a new DataFrame
file_contents = pd.read_csv('dataframe.csv')

# Display the contents of the new DataFrame
print(file_contents)


      name  age  gender  occupation
0  Aravind   23    Male  Programmer
1   Ritwik   34    Male     Manager
2    Harry   45    Male     Analyst
3      Lal   28    Male     Teacher
4     Malu   33  Female     Manager
5   Nirupa   36  Female     Analyst
6    Grace   29  Female  Programmer
7    Annie   40  Female     Manager
8    Akhil   22    Male     Analyst
9     Maya   26  Female     Teacher
